# Import modules

import paho.mqtt.client as mymqtt
import time

# Subscribe to temperature sensor data generated by server
mqtt_topic = 'Test/Temperature'
mqtt_server = 'broker.hivemq.com'

# Subscribe to data published by publisher.py
def on_connect(client, userdata, flags, rc):
    print('Connected with result '+ str(rc))
    client.subscribe(mqtt_topic)

# Display data published
def on_message(client1, userdata, msg):
    print(msg.topic +' '+ str(msg.payload))
    print()

client = mymqtt.Client()
client.on_connect = on_connect
client.on_message = on_message
client.connect(mqtt_server,1883,60)
client.loop_start()

try:
    while True:
        time.sleep(2)
except KeyboardInterrupt:
    # End infinite loop using Ctrl+C in command prompt
    client.loop_stop()
    client.disconnect()